# Algorithms and Code Complexity

This notebook is created by Eda AYDIN through by DATAI Team, Udemy.

## Table of Content

* [Algorithms](#1)
* [Algorithms and Code Complexity](#2)
* [Big-0 Notation](#3)
* [Big-O | Omega | Theta](#4)
* [Big-0 Examples](#5)
    * [O(1) Constant](#5_1)
    * [O(n) Linear](#5_2)
    * [O(n^3) Cubic](#5_3)
* [Calculating Scale of Big-O](#6)
* [Interview Questions](#7)


<a class="anchor" id="1"></a>
### Algorithms

- It is a formula written to solve a problem.

In [6]:
def calculation(book_number, average_price):
    return book_number * average_price

print("You have to pay {}TL".format(calculation(5,50)))

You have to pay 250TL


<a class="anchor" id="2"></a>
### Algorithms and Code Complexity

Problem: Arranging numbers from smallest to largest
Algorithms: Sorting

We can solve this problem by using Bubble Sort or Selection Sort algorithms. But, the main question is in here which algorithm works effectively. Here we come across the concept of code complexity.

Example: Square the numbers from 1 to n and add them all up.

$$\sum_{k=1}^{n} k^{2} = 1^{2} + 2^{2} + 3^{2} + 4^{2} + ... n^{2} = \frac{n(n+1)(2n+1))}{6}$$


In [7]:
def square_sum1(n):
    # Take an input of n and return the sum of the squares of numbers from 0 to n.

    total = 0
    for i in range(n+1):
        total += i**2

    return total

In [8]:
square_sum1(6)

91

In [11]:
def square_sum2(n):
    # Take an input of n and return the sum of the squares of numbers from 0 to n with formula

    return int((n * ( n + 1 )*( 2 * n + 1))/6)

In [12]:
square_sum2(6)

91

**%timeit :** Python timeit() is a method in Python library to measure the execution time taken by the given code snippet.

In [13]:
%timeit square_sum1(6)

2.41 µs ± 40.5 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [14]:
%timeit square_sum2(6) # More fastly

335 ns ± 8.75 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


The results give different results on each computer. The reason is that computers hardware and CPU are different. Also, because runtime is hardware dependent, **Big O notation** is used to compare these two methods, not the concept of time.

<a class="anchor" id="3"></a>
### Big O Notation

* Don't compare by runtime when comparing two algorithms.
* The concept of Big-O Notation refers to the growth of a function.
* Big-O notation analysis is also called asymptotic analysis.
* n refers to size of an input.

\begin{matrix}
\mathbf{Big-O }& \mathbf{Name} \\
1 & Constant\\
log(n) & Logarithmic\\
n & Linear\\
nlog(n) & Log Linear\\
n^2 & Quadratic\\
n^3 & Cubic\\
2^n & Exponential
\end{matrix}

<center><img src="plot_big_o.png"/></center>

<a class="anchor" id="4"></a>
### Big O | Omega | Theta

* **Big-O:** To test how the code we wrote works in the **worst** case
* **Omega:** To test how the code we wrote works in the **best** case
* **Theta:** To test how the code we wrote works in the **mid** case scenario.

In [15]:
a = [2,3,4]
b = [3,2,4]
c = [4,3,2]

In [27]:
%timeit  next((i for i in a if i == 2), None)  # Omega

525 ns ± 13.4 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [28]:
%timeit  next((i for i in b if i == 2), None)  # Theta

559 ns ± 6.95 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [29]:
%timeit  next((i for i in c if i == 2), None) # Big - O

585 ns ± 5.16 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


<a class="anchor" id="5"></a>
### Big-O Examples

<a class="anchor" id="5_1"></a>
#### O(1) Constant

- It doesn't depend on input size.
- If the input size is large, the time complexity doesn't change.

In [2]:
def constant_big_O(list):
    print(list[0])

lst = [-5,0,1,2,3,4,5,6]
constant_big_O(lst)

-5


<a class="anchor" id="5_2"></a>
#### O(n) Linear

- This functions works in linear time. In other words, the number of operations in the algorithm is directly proportional to the input size.

In [3]:
def linear_big_O(list):
    for i in list:
        print(i)

linear_big_O(lst)

-5
0
1
2
3
4
5
6


<a class="anchor" id="5_3"></a>
#### O(n^3) Cubic

* It includes nested loops.

In [29]:
import numpy as np
lst2 = [1,2,3]
def cubic_big_O(list):
    a = []

    for i in range(0,len(list)):
        for j in range(0,len(list)):
            for k in range(0,len(list)):
                a.append([list[i], list[j],list[k]])

    a = np.array(a)
    print(a)

cubic_big_O(lst2)

[[1 1 1]
 [1 1 2]
 [1 1 3]
 [1 2 1]
 [1 2 2]
 [1 2 3]
 [1 3 1]
 [1 3 2]
 [1 3 3]
 [2 1 1]
 [2 1 2]
 [2 1 3]
 [2 2 1]
 [2 2 2]
 [2 2 3]
 [2 3 1]
 [2 3 2]
 [2 3 3]
 [3 1 1]
 [3 1 2]
 [3 1 3]
 [3 2 1]
 [3 2 2]
 [3 2 3]
 [3 3 1]
 [3 3 2]
 [3 3 3]]


<a class="anchor" id="6"></a>
### Calculating Scale of Big-O

* Insignificant constant
* Linear Big-O directly proportional with input size.
* First example Big-O: O(n)
* Second Example Big-O: O(2n)
* number( 1,2,3,, etc.) is insignificant constant

In [30]:
def linear_big_O(list):
    for i in list:
        print(i)

linear_big_O([1,3])   # O(n)

1
3


In [31]:
def linear_big_O_2(list):
    for i in list:
        print(i)
    for i in list:
        print(i)

linear_big_O_2([1,3])   # O(2n)

1
3
1
3


In [32]:
# O(1+n)
def example(list):

    print(list[0])  # O(1) constant

    for i in list:  # O(n) linear
        print(i)

example([1,2,3,4])

1
1
2
3
4


<a class="anchor" id="7"></a>
### Interview Questions

* Why is big-O used instead of runtime?
     * It is not easy for us to know the actual runtime of the algorithm due to hardware differences.
* What does Big-O simply do?
     * It uses for algorithms performance comparison.
* Why is input important to you?
     * Big-O also uses input size.
* Is asymptotic analysis the same as big-O?
     *yes :)
* Is best case or worst case important when writing algorithms?
     * Worst case is important.