# NumPy Basics

This notebook is created by Eda AYDIN through by Udemy, DATAI Team.

In [1]:
import numpy as np

In [2]:
array= np.array([1,2,3,4,5])

In [3]:
array

array([1, 2, 3, 4, 5])

In [4]:
array2 = np.array([1,2,3,4,5,6,7,8,9,10])

In [5]:
array2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## reshape()

In [9]:
# reshape(row,column)
array3 = array2.reshape(2,5)
array3

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

## shape

In [24]:
array.shape # 1 row, 5 column

(5,)

In [13]:
array2.shape # 1 row, 10 column

(10,)

In [10]:
array3.shape #2 row, 5 column

(2, 5)

## ndim : Dimension

In [23]:
array.ndim # 1 row = 1 dimension

1

In [12]:
array2.ndim # 1 row = 1 dimension

1

In [11]:
array3.ndim #2 row = 2 dimension

2

## dtype : Data type

In [22]:
array.dtype

dtype('int32')

In [17]:
array2.dtype

dtype('int32')

In [18]:
array3.dtype

dtype('int32')

## size

In [21]:
array.size

5

In [19]:
array2.size

10

In [20]:
array3.size

10

## Multidimensional Array

np.array should take a list. Don't forget this!

In [26]:
array_multi = np.array([[1,2,3,4,5],
                        [6,7,8,9,10],
                        [11,12,13,14,15]])
array_multi

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [27]:
array_multi.shape # 3 row, 5 column

(3, 5)

## zeros()

**Why should we do this?**

When we wanted to add an element to the array, we were using the built-in append() function. Since this is something that affects memory, if we say **np.zeros((3,4))** at first, we want it to allocate for me with 3 rows and 4 columns.

In [30]:
A = np.zeros((3,4))
A

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [32]:
A[0,0] = 5
A

array([[5., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

## ones()

In [33]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

## empty()

In [37]:
np.empty((5,6))

array([[1.21334839e-311, 9.78249979e-322, 0.00000000e+000,
        0.00000000e+000, 2.22522494e-307, 5.02034658e+175],
       [6.59335932e-066, 5.11339943e-038, 1.00464922e-070,
        9.16886647e-072, 6.23605707e-038, 3.59751658e+252],
       [8.93185432e+271, 4.76484771e+180, 1.47763641e+248,
        1.16096346e-028, 7.69165785e+218, 1.35617292e+248],
       [1.24075807e-047, 1.56092149e+184, 6.29799565e-066,
        7.56533048e-067, 5.88761603e-144, 1.16097020e-028],
       [9.15560124e-072, 1.48220258e-071, 2.00538126e-052,
        1.11763122e+261, 1.16318408e-028, 2.62459060e-306]])

## arange()

**Format:** $$np.arange(start,
                      stop,
                      step,
                      dtype=None,
                      *,
                      like=None)$$

Values are generated within the half-open interval [start, stop) (in other words, the interval including start but excluding stop). For integer arguments the function is equivalent to the Python built-in range function, but returns an ndarray rather than a list.

### Parameters

**start :**
- integer or real,optional
- The interval includes this value.
- The default value is 0.

**stop :**
- integer or real
- The interval does not include this value, except in some cases where step is not an integer and floating point round-off affects the length of out.

**step :**
- integer of real, optional
- Spacing between values.
- The default step size is 1.
- If step is specified as a position argument, start must also be given.

**dtype :**
- dtype
- The output of the output array
- If dtype is not given, infer the data type from the other input arguments.

**like :**
- array_like
- Reference object to allow the creation of arrays which are not NumPy arrays.


### Returns

**arange :**
- array of evenly spaced values

[https://numpy.org/doc/stable/reference/generated/numpy.arange.html](https://numpy.org/doc/stable/reference/generated/numpy.arange.html)

In [38]:
np.arange(10,50,5)

array([10, 15, 20, 25, 30, 35, 40, 45])

## linspace()

**Format:** $$np.linspace(start, stop, num, endpoint = True, restep = False, dtype = None, axis = 0)$$

- Return evenly spaced numbers over a specified interval.
- Returns num evenly spaced samples, calculated over the interval [start,stop].
- The endpoint of the interval can optionally be excluded.

### Parameters

**start:**
- array_like
- The starting value of the sequence

**stop:**
- array_like
- The end value of the sequence, unless endpoint is set to False.

**num:**
- int, optional
- Number of samples to generate
- Default is 50
- Must be non-negative

**endpoint:**
- bool,optional
- If True, return (samples, step), where step is the spacing between samples

**dtype:**
- dtype, optional
- The type of the output array.
- If the dtype is not given, the data type is inferred from start and stop.
- The inferred dtype will never be an integer; float is chosen even if the arguments would produce an array of integers.

**axis:**
- int,optional
- The axis in the result to store the samples.
- Relevant only if start or stop are array-like.
- By default (0), the samples will be along a new axis inserted at the beginning.
- Use -1 to get an axis at the end.

### Returns

**samples:**
- ndarray
- There are num equally spaced in the closed interval [start, stop] or half-open interval [start, stop)

**step:**
- float, optional
- Only returned if retstep is True
- Size of spacing between samples.

[https://numpy.org/doc/stable/reference/generated/numpy.linspace.html](https://numpy.org/doc/stable/reference/generated/numpy.linspace.html)

In [39]:
np.linspace(10,50,20)

array([10.        , 12.10526316, 14.21052632, 16.31578947, 18.42105263,
       20.52631579, 22.63157895, 24.73684211, 26.84210526, 28.94736842,
       31.05263158, 33.15789474, 35.26315789, 37.36842105, 39.47368421,
       41.57894737, 43.68421053, 45.78947368, 47.89473684, 50.        ])

# NumPy Basic Operations

In [47]:
a = np.array([1,2,3])
b = np.array([4,5,6])

In [48]:
a + b

array([5, 7, 9])

In [49]:
a - b

array([-3, -3, -3])

In [50]:
a ** 2

array([1, 4, 9], dtype=int32)

In [51]:
b ** 2

array([16, 25, 36], dtype=int32)

In [52]:
np.sin(a)

array([0.84147098, 0.90929743, 0.14112001])

In [53]:
a < 2

array([ True, False, False])

In [54]:
c =np.array([[1,2,3], [4,5,6]])
d = np.array([[1,2,3],[4,5,6]])

In [56]:
# Hadamard Product - Element Wise Product
c * d

array([[ 1,  4,  9],
       [16, 25, 36]])

In [60]:
# Matrix Product
c.dot(d)

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

It is possible to multiply the vectors (2,3) and (3,2) in the matrix product. That's why the transpose of vector d needs to be taken.

In [61]:
# Matrix Product
c.dot(d.T)

array([[14, 32],
       [32, 77]])

In [62]:
# Matrix Product
c.dot(d.transpose())

array([[14, 32],
       [32, 77]])

In [63]:
np.exp(c)

array([[  2.71828183,   7.3890561 ,  20.08553692],
       [ 54.59815003, 148.4131591 , 403.42879349]])

In [67]:
e = np.random.random((4,5))
e

array([[0.86082011, 0.31595327, 0.57620821, 0.05548578, 0.25501545],
       [0.37033683, 0.09541074, 0.23772126, 0.98789745, 0.18718909],
       [0.6952814 , 0.67110539, 0.92728939, 0.95048186, 0.58448626],
       [0.35272815, 0.09719561, 0.00369474, 0.06901677, 0.91147713]])

In [68]:
e.sum()

9.204794877768679

In [69]:
e.max()

0.9878974497568586

In [70]:
e.min()

0.003694736720741165

In [71]:
e.sum(axis=0)

array([2.27916648, 1.179665  , 1.7449136 , 2.06288186, 1.93816794])

axis = 0 means sum the columns in themselves.

In [72]:
e.sum(axis=1)

array([2.06348283, 1.87855536, 3.82864429, 1.4341124 ])

axis = 1 means sum the rows in themselves.

In [73]:
np.sqrt(e) #square root

array([[0.92780392, 0.56209721, 0.7590838 , 0.23555421, 0.50499055],
       [0.60855306, 0.30888628, 0.48756667, 0.9939303 , 0.43265354],
       [0.83383535, 0.81921022, 0.96295867, 0.97492659, 0.76451701],
       [0.59390921, 0.3117621 , 0.06078435, 0.26271043, 0.95471311]])

In [74]:
np.square(e)

array([[7.41011266e-01, 9.98264708e-02, 3.32015902e-01, 3.07867218e-03,
        6.50328806e-02],
       [1.37149365e-01, 9.10320851e-03, 5.65113967e-02, 9.75941371e-01,
        3.50397554e-02],
       [4.83416219e-01, 4.50382438e-01, 8.59865614e-01, 9.03415760e-01,
        3.41624191e-01],
       [1.24417145e-01, 9.44698641e-03, 1.36510794e-05, 4.76331483e-03,
        8.30790561e-01]])

In [75]:
np.add(e,e)

array([[1.72164022, 0.63190655, 1.15241642, 0.11097157, 0.5100309 ],
       [0.74067365, 0.19082147, 0.47544252, 1.9757949 , 0.37437818],
       [1.39056279, 1.34221077, 1.85457878, 1.90096371, 1.16897253],
       [0.70545629, 0.19439122, 0.00738947, 0.13803354, 1.82295426]])

# Indexing and Slicing

In [84]:
array4 = np.array([1,2,3,4,5,6,7,8,9,10])

In [85]:
print(array4[0])

1


In [79]:
array4[0:4]

array([1, 2, 3, 4])

In [97]:
reverse_array = array4[::-1]
print(reverse_array)

[10  9  8  7  6  5  4  3  2  1]


In [98]:
array5 = np.array([[1,2,3,4,5],
                   [6,7,8,9,10]])
print(array5)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [87]:
array5[1,1]

7

In [89]:
array5[1,3]

9

In [95]:
print(array5[:,1])

[2 7]


In [94]:
print(array5[1,1:4])

[7 8 9]


In [96]:
print(array5[-1,:])

[ 6  7  8  9 10]


In [99]:
print(array5[:,-1])

[ 5 10]


# Shape Manipulation

In [105]:
array6 = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])
print(array6)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


- ravel() : Return a contiguous flattened array.

In [102]:
# flatter
f = array6.ravel()
print(f)

[1 2 3 4 5 6 7 8 9]


In [103]:
array7 = f.reshape(3,3)
print(array7)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [106]:
arrayT = array6.transpose()
print(arrayT)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [107]:
array8 = np.array([[1,2],
                   [3,4],
                   [5,6]])
print(array8)

[[1 2]
 [3 4]
 [5 6]]


In [109]:
print(array8.reshape(2,3))

[[1 2 3]
 [4 5 6]]


## Difference between resize() and reshape()

-resize() : Return a new array with the specified shape.
-reshape(): Gives a new shape to an array without changing its data.

# Stacking Arrays

In [110]:
array9 = np.array([[1,2],
                   [3,4],
                   [5,6]])

array10 = np.array([[-1,-2],
                    [-3,-4],
                    [-5,-6]])

In [113]:
array_vstack = np.vstack((array9,array10))
print(array_vstack)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [-1 -2]
 [-3 -4]
 [-5 -6]]


In [114]:
array_hstack = np.hstack((array9,array10))
print(array_hstack)

[[ 1  2 -1 -2]
 [ 3  4 -3 -4]
 [ 5  6 -5 -6]]


# Convert and Copy Array

In [120]:
list1 = [1,2,3,4]
array11 = np.array(list1)
print(array11)

[1 2 3 4]


In [124]:
list2 = array11.tolist()
print(list2)

[1, 2, 3, 4]


In [125]:
g = np.array([1,2,3])
h = g
j = h

In [128]:
h

array([1, 2, 3])

In [129]:
j

array([1, 2, 3])

In [130]:
h[0] = 5

In [131]:
print(g)
print(h)
print(j)

[5 2 3]
[5 2 3]
[5 2 3]


If we want to create a copy array in the different location:

In [133]:
g = np.array([1,2,3])

In [134]:
h = g.copy()
print(h)

[1 2 3]


In [135]:
h[0] = 5

In [136]:
print(g)
print(h)

[1 2 3]
[5 2 3]
